// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SearchTamplate interface {
	IsSearchTamplate()
}

type ListData struct {
	ID     string    `json:"id"`
	Type   string    `json:"type"`
	Poster []*Poster `json:"poster"`
}

func (ListData) IsSearchTamplate() {}

type Poster struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type ScoreCard struct {
	ID    string  `json:"id"`
	Teams []*Team `json:"teams"`
}

type ScoreCardData struct {
	ID        string       `json:"id"`
	Type      string       `json:"type"`
	ScoreCard []*ScoreCard `json:"score_card"`
}

func (ScoreCardData) IsSearchTamplate() {}

type Team struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
